DogMatcher/Controllers/DogMatcherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DogMatcher.Models;

namespace DogMatcher.Controllers
{
    public class DogMatcherController : Controller
    {
        //
        // GET: /DogMatcher/

        [HttpGet]
        public ActionResult DogChooseForm()
        {
            return View();
        }


        [HttpPost]
        public ActionResult DogChooseForm(Dog dreamDog)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }
            else
            {
                Dog bestMatch = MatchDog(dreamDog);
                return View("DogMatchForm", bestMatch);
            }
        }

        private Dog MatchDog(Dog dreamDog)
        {
            List<Dog> dogs = MakeDatabase();

            Dog bestMatchDog = dogs[0];
            int bestMatchValue = int.MinValue;

            foreach (Dog dog in dogs)
            {
                int matchVal = CalculateMatchValue(dreamDog, dog);
                if (matchVal > bestMatchValue)
                {
                    bestMatchValue = matchVal;
                    bestMatchDog = dog;
                }
            }


            return bestMatchDog;
        }

        private int CalculateMatchValue(Dog dreamDog, Dog dog)
        {
            int matchValue = 0;

            //If the dreamdog must be good with children and this dog is then add a match point
            if (dreamDog.GoodWithChildren == true && dog.GoodWithChildren == true)
            {
                matchValue++;
            }
            else
            {
                //If the dreamdog does not need to be good with children
                if (dreamDog.GoodWithChildren == false)
                {
                    matchValue++;
                }
            }

            //If the dreamdog must not drool and this dog does not drool then add a match point
            if (dreamDog.Drools == false && dog.Drools == false)
            {
                matchValue++;
            }
            else
            {
                //If the dreamdog is allowed to drool then add a match point
                if (dreamDog.Drools == true)
                {
                    matchValue++;       
                }
            }

            //If the dreamdogs size matches this dogs size add two match points
            if (dreamDog.Size == dog.Size)
            {
                matchValue += 2;
            }

            //If the dreamdogs coat lenth matches this dogs coat length add a match point
            if (dreamDog.CoatLength == dog.CoatLength)
            {
                matchValue++;   
            }

            //If the dreamDogs activity level is no preference add a match point
            if (dreamDog.ActivityLevel == Dog.EScale.NoPreference)
            {
                matchValue++;
            }
            else
            {
                //If the dreamDogs activity level matches this dogs activity level
                if (dreamDog.ActivityLevel == dog.ActivityLevel)
                {
                    matchValue++;
                }
            }

            //If the dreamDogs shedding level is no preference add a match point
            if (dreamDog.SheddingLevel == Dog.EScale.NoPreference)
            {
                matchValue++;
            }
            else
            {
                //If the dreamDogs shedding level matches this dogs activity level
                if (dreamDog.SheddingLevel == dog.SheddingLevel)
                {
                    matchValue++;
                }
            }

            //If the dreamDogs grooming level is no preference add a match point
            if (dreamDog.GroomingLevel == Dog.EScale.NoPreference)
            {
                matchValue++;
            }
            else
            {
                //If the dreamDogs grooming level matches this dogs activity level
                if (dreamDog.GroomingLevel == dog.GroomingLevel)
                {
                    matchValue++;
                }
            }

            //If the dreamDogs intelligence level is no preference add a match point
            if (dreamDog.IntelligenceLevel == Dog.EScale.NoPreference)
            {
                matchValue++;
            }
            else
            {
                //If the dreamDogs intelligence level matches this dogs activity level
                if (dreamDog.IntelligenceLevel == dog.IntelligenceLevel)
                {
                    matchValue++;
                }
            }

            return matchValue;
        }

        private List<Dog> MakeDatabase()
        {
            List<Dog> newDatabase = new List<Dog>();

            Dog afghanHound = new Dog();
            afghanHound.BreedName = "afghanHound";
            afghanHound.DisplayName = "Afghan Hound";
            afghanHound.ActivityLevel = Dog.EScale.High;
            afghanHound.CoatLength = Dog.ELength.Long;
            afghanHound.Drools = false;
            afghanHound.GoodWithChildren = false;
            afghanHound.GroomingLevel = Dog.EScale.High;
            afghanHound.IntelligenceLevel = Dog.EScale.Low;
            afghanHound.SheddingLevel = Dog.EScale.High;
            afghanHound.Size = Dog.ESize.Large;
            afghanHound.ImageName = "AfghanHound.jpg";
            newDatabase.Add(afghanHound);


            Dog bassetHound = new Dog();
            bassetHound.BreedName = "BassetHound";
            bassetHound.DisplayName = "Basset Hound";
            bassetHound.ActivityLevel = Dog.EScale.Medium;
            bassetHound.CoatLength = Dog.ELength.Short;
            bassetHound.Drools = true;
            bassetHound.GoodWithChildren = true;
            bassetHound.GroomingLevel = Dog.EScale.Low;
            bassetHound.IntelligenceLevel = Dog.EScale.Medium;
            bassetHound.SheddingLevel = Dog.EScale.Low;
            bassetHound.Size = Dog.ESize.Medium;
            bassetHound.ImageName = "BassetHound.jpg";
            newDatabase.Add(bassetHound);

            Dog beagle = new Dog()
            {
                BreedName = "Beagle",
                DisplayName = "Beagle",
                ActivityLevel = Dog.EScale.High,
                CoatLength = Dog.ELength.Short,
                Drools = false,
                GoodWithChildren = true,
                GroomingLevel = Dog.EScale.Medium,
                IntelligenceLevel = Dog.EScale.Medium,
                SheddingLevel = Dog.EScale.Low,
                Size = Dog.ESize.Medium,
                ImageName = "Beagle.jpg"
            };
            newDatabase.Add(beagle);

            Dog bichonFrise = new Dog()
            {
                BreedName = "BichonFrise",
                DisplayName = "Bichon Frise",
                ActivityLevel = Dog.EScale.High,
                CoatLength = Dog.ELength.Medium,
                Drools = false,
                GoodWithChildren = true,
                GroomingLevel = Dog.EScale.High,
                IntelligenceLevel = Dog.EScale.High,
                SheddingLevel = Dog.EScale.Low,
                Size = Dog.ESize.Small,
                ImageName = "Bichonfrise.jpg"
            };
            newDatabase.Add(bichonFrise);



            Dog borzoi = new Dog()
            {
                BreedName = "Borzoi",
                DisplayName = "Borzoi",
                ActivityLevel = Dog.EScale.High,
                CoatLength = Dog.ELength.Long,
                Drools = false,
                GoodWithChildren = false,
                GroomingLevel = Dog.EScale.High,
                IntelligenceLevel = Dog.EScale.High,
                SheddingLevel = Dog.EScale.High,
                Size = Dog.ESize.Large,
                ImageName = "Borzoi.jpg"
            };
            newDatabase.Add(borzoi);

            Dog bulldog = new Dog()
            {
                BreedName = "Bulldog",
                DisplayName = "Bull Dog",
                ActivityLevel = Dog.EScale.Medium,
                CoatLength = Dog.ELength.Short,
                Drools = true,
                GoodWithChildren = false,
                GroomingLevel = Dog.EScale.Low,
                IntelligenceLevel = Dog.EScale.Medium,
                SheddingLevel = Dog.EScale.Low,
                Size = Dog.ESize.Medium,
                ImageName = "Bulldog.jpg"
            };
            newDatabase.Add(bulldog);


            Dog cav = new Dog()
            {
                BreedName = "CavalierKingCharlesSpaniel",
                DisplayName = "Cavalier King Charles Spaniel",
                ActivityLevel = Dog.EScale.Medium,
                CoatLength = Dog.ELength.Medium,
                Drools = false,
                GoodWithChildren = true,
                GroomingLevel = Dog.EScale.High,
                IntelligenceLevel = Dog.EScale.Medium,
                SheddingLevel = Dog.EScale.Medium,
                Size = Dog.ESize.Small,
                ImageName = "CavalierKingCharlesSpaniel.jpg"
            };
            newDatabase.Add(cav);


            Dog chowchow = new Dog()
            {
                BreedName = "Chowchow",
                DisplayName = "Chow Chow",
                ActivityLevel = Dog.EScale.Medium,
                CoatLength = Dog.ELength.Long,
                Drools = true,
                GoodWithChildren = false,
                GroomingLevel = Dog.EScale.High,
                IntelligenceLevel = Dog.EScale.High,
                SheddingLevel = Dog.EScale.High,
                Size = Dog.ESize.Large,
                ImageName = "Chowchow.jpg"
            };
            newDatabase.Add(chowchow);

            Dog dalmation = new Dog()
            {
                BreedName = "Dalmation",
                DisplayName = "Dalmation",
                ActivityLevel = Dog.EScale.High,
                CoatLength = Dog.ELength.Short,
                Drools = false,

DogMatcher/Views/DogMatcher/DogChooseForm.cshtml
@model DogMatcher.Models.Dog
@{
    ViewBag.Title = "Choose Your Dog";
}

<br />
<h3 class="centered">We'll Help You Choose the Perfect Dog</h3>
@using (Html.BeginForm("DogChooseForm", "DogMatcher", FormMethod.Post))
{
    <fieldset>
        <legend>Preferences</legend>
        <div class="desktopLeft">
        <b class="rbGroupLabel">Must be good with children:</b><br />
        @Html.RadioButtonFor(m => m.GoodWithChildren, true, new { id = "goodWithChildren", @checked = "checked", @class="twoOptions" })<label class="first" for="goodWithChildren">Yes</label>
        @Html.RadioButtonFor(m => m.GoodWithChildren, false, new { id = "notGoodWithChildren", @class = "twoOptions" })<label class="last" for="notGoodWithChildren">Don't Care</label>
        @Html.ValidationMessageFor(m => m.GoodWithChildren)
        <b class="rbGroupLabel">Drooling:</b><br />
        @Html.RadioButtonFor(m => m.Drools, false, new { id = "noDrool", @checked = "checked", @class = "twoOptions" })<label class="first" for="noDrool">No Drooling</label>
        @Html.RadioButtonFor(m => m.Drools, true, new { id = "droolDontCare", @class = "twoOptions" })<label class="last" for="droolDontCare">Don't Mind</label>
        @Html.ValidationMessageFor(m => m.Drools)
        <b class="rbGroupLabel">Coat Length:</b><br />
        @Html.RadioButtonFor(m => m.CoatLength, "Short", new { id = "coatShort", @checked = "checked" })<label class="first" for="coatShort">Short</label>
        @Html.RadioButtonFor(m => m.CoatLength, "Medium", new { id = "coatMedium" })<label for="coatMedium">Medium</label>
        @Html.RadioButtonFor(m => m.CoatLength, "Long", new { id = "coatLong" })<label class="last" for="coatLong">Long</label>
        @Html.ValidationMessage("CoatLength")
        </div>
        <div class="table" id="prefTab">
            <div class="row headerRow">
                <div class="colHead">
                </div>
                <div class="colHead">
                    Low
                </div>
                <div class="colHead">
                    Medium
                </div>
                <div class="colHead">
                    High
                </div>
                <div class="colHead">
                    Any
                </div>
            </div>
            <div class="row">
                <div class="colHead">
                    Activity Level:
                </div>
                <div class="cell">@Html.RadioButtonFor(m => m.ActivityLevel, "Low", new { @class="matrixRB", id="activityLow"})<label class="first" for="activityLow">Low</label>
                </div>
                <div class="cell">@Html.RadioButtonFor(m => m.ActivityLevel, "Medium", new { @class = "matrixRB", id = "activityMed" })<label for="activityMed">Med</label>
                </div>
                <div class="cell">@Html.RadioButtonFor(m => m.ActivityLevel, "High", new { @class = "matrixRB", id = "activityHigh" })<label for="activityHigh">High</label>
                </div>
                <div class="cell">@Html.RadioButtonFor(m => m.ActivityLevel, "NoPreference", new { @class = "matrixRB", id = "activityNP", @checked = "checked" })<label class="last" for="activityNP">Any</label>
                </div>
            </div>
            <div class="row">
                <div class="colHead">
                    Shedding Level:
                </div>
                <div class="cell">@Html.RadioButtonFor(m => m.SheddingLevel, "Low", new { @class = "matrixRB", id = "sheddLow" })<label class="first" for="sheddLow">Low</label>
                </div>
                <div class="cell">@Html.RadioButtonFor(m => m.SheddingLevel, "Medium", new { @class = "matrixRB", id = "sheddMed" })<label for="sheddMed">Med</label>
                </div>
                <div class="cell">@Html.RadioButtonFor(m => m.SheddingLevel, "High", new { @class = "matrixRB", id = "sheddHigh" })<label for="sheddHigh">High</label>
                </div>
                <div class="cell">@Html.RadioButtonFor(m => m.SheddingLevel, "NoPreference", new { @class = "matrixRB", id = "sheddNP", @checked = "checked" })<label class="last" for="sheddNP">Any</label>
                </div>
            </div>
            <div class="row">
                <div class="colHead">
                    Grooming Level:
                </div>
                <div class="cell">@Html.RadioButtonFor(m => m.GroomingLevel, "Low", new { @class = "matrixRB", id = "groomLow" })<label class="first" for="groomLow">Low</label>
                </div>
                <div class="cell">@Html.RadioButtonFor(m => m.GroomingLevel, "Medium", new { @class = "matrixRB", id = "groomMed" })<label for="groomMed">Med</label>
                </div>
                <div class="cell">@Html.RadioButtonFor(m => m.GroomingLevel, "High", new { @class = "matrixRB", id = "groomHigh" })<label for="groomHigh">High</label>
                </div>
                <div class="cell">@Html.RadioButtonFor(m => m.GroomingLevel, "NoPreference", new { @class = "matrixRB", id = "groomNP", @checked = "checked" })<label class="last" for="groomNP">Any</label>
                </div>
            </div>
            <div class="row">
                <div class="colHead">
                    Intelligence Level:
                </div>
                <div class="cell">@Html.RadioButtonFor(m => m.IntelligenceLevel, "Low", new { @class = "matrixRB", id = "intelLow" })<label class="first" for="intelLow">Low</label>
                </div>
                <div class="cell">@Html.RadioButtonFor(m => m.IntelligenceLevel, "Medium", new { @class = "matrixRB", id = "intelMed" })<label for="intelMed">Med</label>
                </div>
                <div class="cell">@Html.RadioButtonFor(m => m.IntelligenceLevel, "High", new { @class = "matrixRB", id = "intelHigh" })<label for="intelHigh">High</label>
                </div>
                <div class="cell">@Html.RadioButtonFor(m => m.IntelligenceLevel, "NoPreference", new { @class = "matrixRB", id = "intelNP", @checked = "checked" })<label class="last" for="intelNP">Any</label>
                </div>
            </div>
        </div>
        @Html.ValidationMessageFor(m => m.ActivityLevel)
        @Html.ValidationMessageFor(m => m.SheddingLevel)
        @Html.ValidationMessageFor(m => m.GroomingLevel)
        @Html.ValidationMessageFor(m => m.IntelligenceLevel)
        <div class="desktopBottomCenter">
        <b>Preferred Size:</b><br />
        @Html.DropDownListFor(m => m.Size, new SelectList(Enum.GetValues(typeof(DogMatcher.Models.Dog.ESize))))
        @Html.ValidationMessageFor(m => m.Size)
        <input type="submit" name="findDog" value="Find My Dog!" />
        </div>
    </fieldset>
}

DogMatcher/Views/DogMatcher/DogMatchForm.cshtml
@model DogMatcher.Models.Dog

@{
    ViewBag.Title = "Your Ideal Dog";
}

<h3 class="centered">Our Recommendation</h3>
<h4 id="suggestion">We suggest the @Model.DisplayName</h4>
<img id="dogImg" src='@Url.Content("~/Content/DogImages/" + Model.ImageName)' alt="Dog Iamge" />
<div id="details">
    <h3>Details</h3>
    <table id="dogTab">
        <tr>
            <td>
                Activity Level
            </td>
            <td>@Model.ActivityLevel.ToString()
            </td>
        </tr>
        <tr>
            <td>
                Shedding Level
            </td>
            <td>@Model.SheddingLevel.ToString()
            </td>
        </tr>
        <tr>
            <td>
                Grooming Level
            </td>
            <td>@Model.GroomingLevel.ToString()
            </td>
        </tr>
        <tr>
            <td>
                Intelligence Level
            </td>
            <td>@Model.IntelligenceLevel.ToString()
            </td>
        </tr>
        <tr>
            <td>
                Good With Children
            </td>
            <td>@Model.GoodWithChildren.ToString()
            </td>
        </tr>
        <tr>
            <td>
                Drools
            </td>
            <td>@Model.Drools.ToString()
            </td>
        </tr>
        <tr>
            <td>
                Coat Length
            </td>
            <td>@Model.CoatLength.ToString()
            </td>
        </tr>
        <tr>
            <td>
                Size
            </td>
            <td>@Model.Size.ToString()
            </td>
        </tr>
    </table>
</div id="details">